name = "ya7-mafia-online"
main = "worker.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "MAFIA_ROOM"
class_name = "MafiaRoom"

[[durable_objects.bindings]]
name = "GOT_ROOM"
class_name = "GotRoom"

[[durable_objects.bindings]]
name = "MAWWIH_ROOM"
class_name = "MawwihRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MafiaRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GotRoom"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["MawwihRoom"]
